dubbo:
  name: adp-sla-service
  registry: zookeeper://127.0.0.1:2181
  port: -1
  timeout: 10000
  threads: 100
  heart-beats: 10000

mybatis:
  type-aliases-package: com.haier.adp.sla.model
  mapper-locations: classpath*:mapper/*Mapper.xml


logging:
  file: ${user.home}/log/adp/sla.log
  level.*: DEBUG

zookeeper:
  host: 127.0.0.1
  port: 2181
